version: "3.5"
services:
  app:
    ports:
      - ${DOCKER_APP_PORT}:${SERVER_PORT}
    build:
      args:
        - HOST_USER_UID=1000
        - HOST_USER_GID=1000
    command: ['npm', 'start']
    command: ["npm", "run"]
  postgres_db:
    ports:
      - ${DOCKER_POSTGRES_PORT}:${POSTGRES_PORT}
  postgres_adminer:
    image: wodby/adminer:4.7
    container_name: example_postgres_adminer
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_HOST=postgres_db
      - ADMINER_DEFAULT_DB_NAME=${POSTGRES_DB}
      - ADMINER_DESIGN=nette
    depends_on:
      - postgres_db
    ports:
      - ${DOCKER_ADMINER_PORT}:9000
    networks:
      - example-back
