version: '3.5'
services:
  app:
    image: example-back
    container_name: example_back
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${DOCKER_APP_PORT}:${SERVER_PORT}
    command: ['npm', 'start']
    networks:
      - example-back
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:12
    container_name: example_postgres
    ports:
      - ${DOCKER_POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data=/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - example-back
  postgres_adminer:
    image: wodby/adminer:4.7
    container_name: example_postgres_adminer
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_HOST=postgres_db
      - ADMINER_DEFAULT_DB_NAME=${POSTGRES_DB}
      - ADMINER_DESIGN=nette
    depends_on:
      - postgres_db
    ports:
      - ${DOCKER_ADMINER_PORT}:9000
    networks:
      - example-back
networks:
  example-back:
    driver: bridge

volumes:
  postgres_data:
